name: restaurant_menu_management
description: A Flutter Restaurant Menu Management app with Firebase.
publish_to: 'none' 
version: 1.0.0+1

#------------------------------------------------------------------------------
# SDK Configuration
#------------------------------------------------------------------------------
environment:
  sdk: ^3.7.0

#------------------------------------------------------------------------------
# App Dependencies
#------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
    
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # UI
  google_fonts: ^6.1.0

#------------------------------------------------------------------------------
# Development Dependencies  
#------------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#------------------------------------------------------------------------------
# Flutter Configuration
#------------------------------------------------------------------------------
flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic