// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; 
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWj-aS1KpX5TgqJy4BNzjVoeiNxkm45SU',
    appId: '1:809262138786:web:109e1bfbb0162de5e75efb',
    messagingSenderId: '809262138786',
    projectId: 'flutterapp2025',
    authDomain: 'flutterapp2025.firebaseapp.com',
    storageBucket: 'flutterapp2025.firebasestorage.app',
    measurementId: 'G-BM3DR2SLQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhd85UxsZnGmJ12vuPuQh_dEJFUw3wro',
    appId: '1:809262138786:android:5e92488716d7f02fe75efb',
    messagingSenderId: '809262138786',
    projectId: 'flutterapp2025',
    storageBucket: 'flutterapp2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYOx2gNMsA0VgDpXBrTJxIcLilrkUKM8Q',
    appId: '1:809262138786:ios:958a13c476d933ebe75efb',
    messagingSenderId: '809262138786',
    projectId: 'flutterapp2025',
    storageBucket: 'flutterapp2025.firebasestorage.app',
    iosBundleId: 'com.example.restaurantMenuManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYOx2gNMsA0VgDpXBrTJxIcLilrkUKM8Q',
    appId: '1:809262138786:ios:958a13c476d933ebe75efb',
    messagingSenderId: '809262138786',
    projectId: 'flutterapp2025',
    storageBucket: 'flutterapp2025.firebasestorage.app',
    iosBundleId: 'com.example.restaurantMenuManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWj-aS1KpX5TgqJy4BNzjVoeiNxkm45SU',
    appId: '1:809262138786:web:109e1bfbb0162de5e75efb',
    messagingSenderId: '809262138786',
    projectId: 'flutterapp2025',
    authDomain: 'flutterapp2025.firebaseapp.com',
    storageBucket: 'flutterapp2025.firebasestorage.app',
    measurementId: 'G-BM3DR2SLQS',
  );
}